lab2:
	#replace the following command with your compilation command
	javac *.java

test1:
	java lab2 test1.asm script1.txt > out.txt
	diff -w -B out.txt output1.txt 
test2:
	java lab2 test2.asm script2.txt > out.txt
	diff -w -B out.txt output2.txt
test3:
	java lab2 test3.asm script3.txt > out.txt
	diff -w -B out.txt output3.txt
