lab6:
	#replace the following command with your compilation command
	javac *.java

test1:
	java lab6 mem_stream.1 > out.txt
	diff -w -B out.txt mem_stream1.out

test2:
	java lab6 mem_stream.2 > out.txt
	diff -w -B out.txt mem_stream2.out

